apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: passotp-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: "letsencrypt-prod" # Descomente se usar cert-manager
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - otp.seudominio.com
      secretName: passotp-tls # Nome do secret com o certificado SSL
  rules:
    - host: otp.seudominio.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: passotp-service
                port:
                  number: 3000
