apiVersion: v1
kind: Secret
metadata:
  name: passotp-secret
  namespace: default
type: Opaque
data:
  # Valores devem ser codificados em base64
  # Exemplo: echo -n "sua-chave-secreta" | base64
  SESSION_SECRET: "MmhSbWJwTlNoVXNqUkhkS3BjYXNZb1RwZWlJdDZRRDlhYmZPa3E1NVlxcz0="
  ENCRYPTION_KEY: "OVRKRjFsNHJRWjRYRjR5R2oxdStSeTlaNGt4UWgyaXpoSzJVTWMwUFlkYz0="
